security:

    # -------------------------------------------------------------------------
    # üîê HASHAGE DES MOTS DE PASSE
    # -------------------------------------------------------------------------
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # -------------------------------------------------------------------------
    # üë§ PROVIDERS : On charge les users par leur email
    # -------------------------------------------------------------------------
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email


    # -------------------------------------------------------------------------
    # üî• FIREWALLS
    # -------------------------------------------------------------------------
    firewalls:

        # Dev profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # ‚≠êÔ∏è FIREWALL PRINCIPAL
        main:
            lazy: true
            provider: app_user_provider

            # Ton authenticator personnalis√©
            custom_authenticator: App\Security\LoginAuthenticator

            # Optionnel : Remember Me
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800   # 7 jours
                path: /
                always_remember_me: true

            # D√©connexion
            logout:
                path: app_logout
                target: app_login


    # -------------------------------------------------------------------------
    # üîí ACCESS CONTROL
    # -------------------------------------------------------------------------
    access_control:

        # Autoriser l'acc√®s public au login
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Si √† l'avenir tu veux un /admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Toute la zone app /home /fiche-client etc
        - { path: ^/, roles: ROLE_USER }



when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
