vich_uploader:
    db_driver: orm

    mappings:
        fiche_images:
            uri_prefix: /uploads/clients
            upload_destination: '%kernel.project_dir%/public/uploads/clients'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
